In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('test_scores.csv')
df.head()

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83

In [10]:
x = np.array(df['math'])
y = np.array(df['cs'])

In [11]:
n = df.shape[0]

In [34]:
iterations = 1000
lr = 0.001
m = 0
b = 0
x*(y - (m*x + b))
sum(x*(y - (m*x + b)))

49459

In [40]:
m = 1
b = 0
print(y  - (m*x + b))
sum(np.square(y  - (m*x + b)))

[ 6 12 -7 10  3  3  1 -5  2  6]


413

In [58]:
iterations = 1000000
lr = 0.0002
m = 0
b = 0
for i in range(iterations):
  dm = -(2/n)*(sum(x*(y - (m*x + b))))
  db = -(2/n)*(sum((y - (m*x + b))))
  m = m - lr*dm
  b = b - lr*db
  cost = (1/n)*sum(np.square(y  - (m*x + b)))
  print('iteration:',i, 'm:', m,'b:', b, 'cost:', cost)

In [59]:
print(m)
print(b)

1.0204362751212823
1.7238746787923669


In [52]:
from sklearn.linear_model import LinearRegression
model = LinearRegression() 
model.fit(np.array(df['math']).reshape(10,1), np.array(df['cs']).reshape(10,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [53]:
model.coef_

array([[1.01773624]])

In [54]:
model.intercept_

array([1.91521931])