In [1]:
import numpy as np, pandas as pd

In [2]:
from sklearn.datasets import load_iris
df = load_iris()

In [3]:
x = df['data']
y = df['target']

In [4]:
from sklearn.model_selection import train_test_split, cross_val_score
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)


In [9]:
def get_score(model, x_train, x_test, y_train, y_test):
  score = cross_val_score(model, x_train, y_train, cv = 4)
  return score


In [6]:
from sklearn.linear_model import  LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [11]:
get_score(LogisticRegression(solver='liblinear'),x_train, x_test, y_train, y_test)

array([1.        , 0.86666667, 0.93333333, 1.        ])

In [12]:
get_score(SVC(),x_train, x_test, y_train, y_test)


array([1.        , 0.96666667, 0.96666667, 0.96666667])

In [13]:
get_score(RandomForestClassifier(n_estimators=40),x_train, x_test, y_train, y_test)


array([0.96666667, 0.9       , 0.96666667, 0.96666667])